---
abstract: 'Notify about recent modules uploaded to CPAN'
author:
  - 'Pavel Shaydo, C<< <zwon at cpan.org> >>'
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MetaCPAN-Gtk2-Notify
no_index:
  directory:
    - inc
    - t
requires:
  File::Slurp: 0
  Gtk2::Notify: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
